name: APKExtractorPRO
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  device_apps: ^1.0.9
  filesize: ^1.0.4
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.7.0
  fluttertoast: ^3.1.3
  loading_animations: ^2.1.0
  open_file: ^3.0.1
  page_transition: ^1.1.5
  path_provider: ^1.6.2
  permission_handler: ^5.0.0+hotfix.6
  provider: ^4.0.1
  share_it: ^0.5.1+3
  shared_preferences: ^0.5.4+5
  store_redirect: ^1.0.2
  toggle_switch: ^0.1.8
  uninstall_apps: ^0.0.4
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher/icon.png"
  image_path_android: "assets/images/launcher/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/launcher/icon.png
    - assets/images/yazeed.png
